### ISSUE TITLE
布隆过滤器误判问题

### ISSUE THREAD

**Issue by CompetitiveLin** [Naccl/ShortURL#1]
https://github.com/Naccl/ShortURL/blob/755fa6ae526af15da06772e6ca5b3e428f048d4c/src/main/java/top/naccl/dwz/service/impl/UrlServiceImpl.java#L80
作者你好！布隆过滤器的误判是指
> 对于已经在集合中的元素，一定可以判定该元素在集合中；对于不在集合中的元素，可能会被误判在集合中。

即在过滤器中找不到的元素一定不在数据库里，因此一定不会出现duplicate元素的插入，catch里的内容也就永远不会执行。
如有错误，请指出。

**Comment by CompetitiveLin** [comment]
还有一点，基于hutool的布隆过滤器每一次重启应用，布隆过滤器里的内容也会清空，因此我能理解为什么要加一个DUPLICATE再生成一次短链接了

**Comment by Naccl** [comment]
是的，这一块的注释确实没写好，因为用hutool嘛，重启应用后布隆清空了，导致已存在的被判断为不存在，说这个是「误判」其实不准确，指的并不是「布隆过滤器的误判」，而是清空导致的，所以catch还是会执行的。而布隆过滤器本身的误判并不影响
https://github.com/Naccl/ShortURL/blob/755fa6ae526af15da06772e6ca5b3e428f048d4c/src/main/java/top/naccl/dwz/service/impl/UrlServiceImpl.java#L68-L70
因为在这里只要判断为存在，就再重新hash一次，误判带来的损失就是多hash一次。
